spring:
  application:
    name: transaction
server:
  port: 8091
  tomcat:
    uri-encoding: UTF-8
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8100/eureka
#redis集群版
redis:
  timeout: 6000ms
  database: 0
  cluster:
    nodes:
      - 192.168.207.88:7001
      - 192.168.207.88:7002
      - 192.168.207.88:7003
      - 192.168.207.88:7004
      - 192.168.207.88:7005
      - 192.168.207.88:7006
    max-redirects: 3 # 获取失败 最大重定向次数
  lettuce:
    pool:
      max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
      max-idle: 10 # 连接池中的最大空闲连接
      min-idle: 5 # 连接池中的最小空闲连接
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）

