spring:
  application:
    name: gateway-server
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 6000ms
      database: 0
      cluster:
        nodes:
          - 192.168.207.88:7001
          - 192.168.207.88:7002
          - 192.168.207.88:7003
          - 192.168.207.88:7004
          - 192.168.207.88:7005
          - 192.168.207.88:7006
        max-redirects: 3 # 获取失败 最大重定向次数
      lettuce:
        pool:
          max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
          max-idle: 10 # 连接池中的最大空闲连接
          min-idle: 5 # 连接池中的最小空闲连接
          max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      #是否与服务发现组件进行结合，通过 serviceId 转发到具体的服务实例。
      #默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
      routes:
        - id: api-authorization
          uri: lb://AUTHORIZATION
          predicates:
            - Path=/api-authorization/*
          filters:
            - StripPrefix=1
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug
