server:
  port: 8085

spring:
  application:
    name: redission-test
  # redis配置
  redis:
    database: 11
    host: 127.0.0.1
    port: 6379
    timeout: 10000
  # redisson单机配置
  redisson:
    config:classpath:redisson-single-dev.yml